<a href="https://colab.research.google.com/github/sotesh1516/deep-ML/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import PIL
import numpy
import IPython
from io import BytesIO
from numpy.lib.stride_tricks import sliding_window_view
images = []
targets = []
for i in range(1,5):
  im = PIL.Image.open(f'/content/drive/MyDrive/Colab Notebooks/{i}.jpg').convert('L')
  bio = BytesIO() #treat a chuck of mem as file, since PIL only writes to file obj
  im.save(bio, format="png")
  display(IPython.display.Image(data=bio.getvalue(), format='png'))
  images.append(numpy.asarray(im)/255) #squash from 0-1
  targets.append(i/4) #squash 0.25 to 1

In [3]:
numpy.random.seed(5814)

In [19]:
#a 5x5 conv, no bias
w1 = numpy.random.randn(5,5)
#a 3x3 conv, no bias. will follow a max pool layer
w2 = numpy.random.randn(3,3)
print(w2)
#finally fcl
w3 = numpy.random.randn(5,4)

[[ 0.82678773 -0.85897404  0.84179888]
 [-0.72436561  0.36304398  0.53619642]
 [-0.14690177 -1.28403472 -1.24309088]]


In [20]:
num_epoch = 1000
learning_rate = 0

loss_before_training = 0
loss_after_training = 0

final_output, start_output = numpy.array([[]]), numpy.array([[]])

In [37]:
w4 = numpy.random.randn(2,3)

In [38]:
# this won't work if kernel > input
def my_2dconv(X, weights):
  rows, cols = X.shape
  kernel_rows, kernel_cols = weights.shape

  output_rows = rows - kernel_rows + 1
  output_cols = cols - kernel_cols + 1

  for i in range(rows-kernel_rows+1):
    for j in range(cols-kernel_cols+1):
      window = X[i:i+kernel_rows,j:j+kernel_cols]
      product = (window * weights).sum()

def my_2dconv_backward_input(X, weights, upstream_grad): #return dL/dX
  pass
def my_2dconv_backward_weights(X, weights, upstream_grad): #return dL/dX
  pass

my_2dconv(w2,w4)

[[ 0.82678773 -0.85897404  0.84179888]
 [-0.72436561  0.36304398  0.53619642]]
0.2309934709816708
[[-0.72436561  0.36304398  0.53619642]
 [-0.14690177 -1.28403472 -1.24309088]]
-0.9828397079320572
